<?php echo $this->doctype(). PHP_EOL ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php $this->headTitle()->setSeparator(' - ');
              $this->headTitle('Mon site');
              echo $this->headTitle() . PHP_EOL;
              

		     echo $this->navigation()
		               ->links(Zend_Registry::get('navigation'));

		
              $this->headLink()->appendStylesheet('/css/reset.css', 'all');
              $this->headLink()->appendStylesheet('/css/fonts.css', 'all');
              $this->headLink()->appendStylesheet('/css/style.css', 'all');
              echo $this->headLink() . PHP_EOL;
              
              $this->headScript()->appendFile('/js/less-grid-4.js', 'text/javascript');
              echo $this->headScript() . PHP_EOL;
              
              $this->headMeta()->setHttpEquiv('Content-type', 'text/html; charset=utf-8');
              echo $this->headMeta() . PHP_EOL;
             ?>
</head>
<body id="body">
<div id="top">
	<div id="top_content">
		<div id="logo">
			<h1>loremIpsum</h1>
			<h4>Phasellus malesuada</h4>
		</div>
	</div>
</div>
<div class="menu">
	<div class="menu_content">
		<?php 
		echo $this->navigation()
		     ->menu(Zend_Registry::get('navigation'))
		     ->setUlClass('menulist');
		?>
	</div>
</div>
<div class="breadcrumbs"> 
<a href="/">Mon site ZF</a> -> 

<?php 
		echo $this->navigation()
		          ->breadcrumbs(Zend_Registry::get('navigation'))
		          ->setSeparator(' / ')
		          ->setMinDepth(0);
		?>
</div>
<div id="content">
	<div id="text">
		<?php echo $this->layout()->content?>
	</div>
</div>
<div id="bottom">
	<div id="bottom_content">
		<div class="callcenter">
			<p class="call_us" style="color:#e44038;padding-left:30px;">Suport 24/7: </p>
			<p class="call_us"><img src="/img/phone.png" alt="phone" />  (045)0205968600 or (045)0205968611</p>
			<p class="call_us"><img src="/img/email.png" alt="email" />  contact@contact.com</p>

		</div>
		<div id="menu_bottom_list">
				<div class="menu_bottom" ><a href="" class="bottom_link" > Home </a></div>
				<div class="menu_bottom" ><a href="" class="bottom_link"> Try it </a></div>
				<div class="menu_bottom" ><a href="" class="bottom_link"> Download </a></div>
				<div class="menu_bottom" ><a href="" class="bottom_link"> Documentation </a></div>
				<div class="menu_bottom" ><a href="" class="bottom_link"> About </a></div>
		</div>
		<div class="copyright description">&copy; 2011 Ioana Condor
		</div>
	</div>
</div>
</html>

