<?php 
$this->headMeta()->appendName ('Keywords', 'ip-formation, formation');
$this->headMeta()->appendName ('Description', 'ip-formation, formation');
$this->headTitle('Home page'); // Helper : Gérer dans le layout 
$this->headLink()->appendStylesheet('/css/specifique_page.css', 'screen'); 
?>

<h1>Index <?php echo $this->toto ?></h1>

<p>Date du jour <?php echo $this->formatDate('2011-08-02')?></p>